version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: LARAVEL_BYPASS_ENV_CHECK=1 npm run build
      - run:
          name: "Create database and run migration"
          command: |
            php artisan migrate --env=testing --database=sqlite_testing --force
      - run:
          name: "テスト"
          command: |
            ./vendor/bin/phpunit
  deploy:
    docker:
      - image: cimg/php:8.2-browsers
    steps:
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd datemaki && \
              git pull origin main && \
              composer install -n --no-dev --prefer-dist && \
              npm ci && \
              LARAVEL_BYPASS_ENV_CHECK=1 npm run build && \
              php artisan migrate --force && \
              php artisan config:cache"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
